### ISSUE TITLE
included plog, instantly got error "expected expression"

### ISSUE THREAD

**Issue by Amazonasmann** [SergiusTheBest/plog#114]
They way this lib is supposed to work looks great, so I gave it a try.  But it does not seem to work for me, with even minimal code.
(In my DLL):

>     plog::init(plog::debug, "Hello.txt"); // Step2: initialize the logger.

    LOGD << "Hello log!"; // short macro

Instantly gives me an error "expected expression"
![image](https://user-images.githubusercontent.com/3660464/49138061-827a6e00-f2ee-11e8-9e2a-cd1f01d635c9.png)

I use Visual Studio 2017 compiler, CMake and Qt Creator as IDE. I don't think this is normal. Any ideas? Maybe it does not work with msvc14.1 compiler?
In IDE:
![image](https://user-images.githubusercontent.com/3660464/49138368-4267bb00-f2ef-11e8-9a69-c8684efc5b52.png)

**Comment by SergiusTheBest** [comment]
Is it a compilation error or static analysis error?

**Comment by Amazonasmann** [comment]
Compilation error. From the first look it seems like a static analysis error from the IDE but I can not compile it (picture with error is after I try to compile)

**Comment by SergiusTheBest** [comment]
Can you attach your sample?

**Comment by Amazonasmann** [comment]
Ok give me a few minutes. I will make a simple cmake program

**Comment by Amazonasmann** [comment]
Compiler(from cmake output): 

> The C compiler identification is MSVC 19.16.27023.1
> The CXX compiler identification is MSVC 19.16.27023.1
Now that I used it in a simple test program (shared DLL) it compiles. Maybe I had some other compiling error before, and the IDE made it look the way it is plog's fault. 

Anyway...I will not able to use PLOG since it will completely spam my IDE full with issues and errors, see this image:
![image](https://user-images.githubusercontent.com/3660464/49142215-91661e00-f2f8-11e8-8c38-83aa256217ca.png)

For completion I added the sample project with CMake. I use Qt Creator with MSVC17 compiler to open it and generate files. I did not test it with another IDE, it could be that the visual studio compiler is complaining and not Qt Creator IDE directly
[TestDLL.zip](https://github.com/SergiusTheBest/plog/files/2623722/TestDLL.zip)

**Comment by SergiusTheBest** [comment]
I'll check it in Qt Creator, it looks like a static analysis error (as it doesn't understand `__if_exists` extension). Meanwhile you can change:
```cpp
#if defined(_MSC_VER) && _MSC_VER >= 1600 && !defined(__INTELLISENSE__) && !defined(__INTEL_COMPILER) // >= Visual Studio 2010, skip IntelliSense and Intel Compiler
#   define PLOG_GET_THIS()      __if_exists(this) { this } __if_not_exists(this) { 0 }
#else
#   define PLOG_GET_THIS()      reinterpret_cast<void*>(0)
#endif
```
to
```cpp
//#if defined(_MSC_VER) && _MSC_VER >= 1600 && !defined(__INTELLISENSE__) && !defined(__INTEL_COMPILER) // >= Visual Studio 2010, skip IntelliSense and Intel Compiler
//#   define PLOG_GET_THIS()      __if_exists(this) { this } __if_not_exists(this) { 0 }
//#else
#   define PLOG_GET_THIS()      reinterpret_cast<void*>(0)
//#endif
```
in Log.h.

**Comment by Amazonasmann** [comment]
Awesome. This does it restricted my usage of the framework?
Maybe you can think of something and add it to the framework in future versions. Thanks!

**Comment by SergiusTheBest** [comment]
> does it restricted my usage of the framework?

No. It's a small feature that gets `this` pointer value and prints it to csv logs.

**Comment by SergiusTheBest** [comment]
I pushed the fix, please try it.

**Comment by Amazonasmann** [comment]
Yup, works. Well done

**Comment by domenn** [comment]
I have a similiar problem. Happens when using Visual Studio 2017. On mouse hover error message is "Cannot resolve symbol 'ref'.
In error list: class "plog::Record" has no member "ref"

Happens when using any log macro, for example 
`LOG_DEBUG << "anything";`
It is only static analysis error. Compiles and works OK. 
Macro expands to:
`if (!plog::get<0>() || !plog::get<0>()->checkSeverity(plog::debug)) {;} else (*plog::get<0>()) += plog::Record(plog::debug, __FUNCTION__, 25, "", __if_exists(this) { this } __if_not_exists(this) { 0 }).ref() << "anything";`
